########## PROFESSIONALS ##########

### CREATE PROFESSIONAL
POST http://localhost:8080/cardiacrc/api/professionals
Content-Type: application/json

{ "username": "ryanbaker",
  "licenseNumber": "438942035",
  "name": "Ryan Baker",
  "password": "12345",
  "email": "ryan.baker@mail.com"
}

### GET ALL PROFESSIONALS
GET http://localhost:8080/cardiacrc/api/professionals
Accept: application/json

### GET PROFESSIONAL DETAILS
GET http://localhost:8080/cardiacrc/api/professionals/tomasalves
Accept: application/json

### GET PROFESSIONAL PATIENTS
GET http://localhost:8080/cardiacrc/api/professionals/ryanbaker/patients
Accept: application/json

### GET PROFESSIONAL PRESCTIPTIONS
GET http://localhost:8080/cardiacrc/api/professionals/ryanbaker/prescriptions
Accept: application/json

### UPDATE PROFESSIONAL
PUT http://localhost:8080/cardiacrc/api/professionals/ryanbaker
Content-Type: application/json

{
  "licenseNumber": "12345679",
  "name": "Bryan",
  "password": "54321",
  "email": "bryan.sucks@no.com"
}

### DELETE PROFESSIONAL
DELETE http://localhost:8080/cardiacrc/api/professionals/ryanbaker
Accept: application/json



########## PATIENTS ##########

### CREATE PATIENT
POST http://localhost:8080/cardiacrc/api/patients
Content-Type: application/json

{ "username": "jackviole",
  "healthNumber": "498274982",
  "name": "Jack Viole",
  "password": "12345",
  "email": "jack.viole@mail.com",
  "professionalUsername": "ryanbaker"
}

### GET ALL PATIENTS
GET http://localhost:8080/cardiacrc/api/patients
Accept: application/json

### GET PATIENT DETAILS
GET http://localhost:8080/cardiacrc/api/patients/jackviole
Accept: application/json

### UPDATE PATIENT
PUT http://localhost:8080/cardiacrc/api/patients/jackviole
Content-Type: application/json

{
  "healthNumber": "999999999",
  "name": "Jack Sparow",
  "password": "98765",
  "email": "cash@money.com",
  "professionalUsername": "tomasalves"
}

### DELETE PATIENT
DELETE http://localhost:8080/cardiacrc/api/patients/jackviole
Accept: application/json

### GET PATIENT PRESCRIPTIONS
GET http://localhost:8080/cardiacrc/api/patients/joaosalvador/prescriptions
Accept: application/json



########## ADMINISTRATORS ##########

### CREATE ADMINISTRATOR
POST http://localhost:8080/cardiacrc/api/administrators
Content-Type: application/json

{ "username": "admin1",
  "name": "ADMIN",
  "password": "000",
  "email": "admin@admin.un"
}

### GET ALL ADMINISTRATORS
GET http://localhost:8080/cardiacrc/api/administrators
Accept: application/json

### GET NUMBER OF ADMINISTRATORS
GET http://localhost:8080/cardiacrc/api/administrators/count
Accept: application/json


### GET ADMINISTRATOR DETAILS
GET http://localhost:8080/cardiacrc/api/administrators/admin1
Accept: application/json

### UPDATE ADMINISTRATOR
PUT http://localhost:8080/cardiacrc/api/administrators/admin1
Content-Type: application/json

{
  "name": "upADd ADMIN",
  "passwordConfirmation": "123456"
}

### DELETE ADMINISTRATOR
DELETE http://localhost:8080/cardiacrc/api/administrators/admin1
Accept: application/json

### Get JWT token
POST http://localhost:8080/cardiacrc/api/auth/login
Content-Type: application/json

{
  "username": "jacksparrow",
  "password": "123456"
}

### Who am I?
GET http://localhost:8080/cardiacrc/api/auth/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2MzY4NTcwNTh9.RfZcbi7reiIaltllsv6kDDQaNdN5N9tETpgGsW2sU_Zp2CUSawyb28R0n4LW-1PbNBFc9uPrsnOTjuYNm3CxSkBomOhkeFvYZRSxim1HMd3x-iJCGNR_5QJsg2h1bYgsIx5NoBWaWZxCkx4j5RpXGXU_YilDdzJTUznZgEoZ-FWbzQ6g1WKz9fmr20zGm7YCr05WV_ujwvI5skZu0SAJv_rK6hn6RlBmrFt-vjQqVd25Ph7wSvb7BvLdJPIs-x9mMJkatSExDPyqS2xEJu9XX49Yf53oMGcRZE-UQIG_qckm752LJU_6kks9F9ycJi11qyJxwADJwbmnaGO3v7wZTQ

####
GET http://localhost:8080/cardiacrc/api/patients/joaosalvador/activePrescriptions
Accept: application/json