########## PROFESSIONALS ##########

### CREATE PROFESSIONAL
POST http://localhost:8080/cardiacrc/api/professionals
Content-Type: application/json

{ "username": "ryanbaker",
  "licenseNumber": "438942035",
  "name": "Ryan Baker",
  "password": "12345",
  "email": "ryan.baker@mail.com"
}

### GET ALL PROFESSIONALS
GET http://localhost:8080/cardiacrc/api/professionals
Accept: application/json

### GET PROFESSIONAL DETAILS
GET http://localhost:8080/cardiacrc/api/professionals/marcopolo
Accept: application/json

### GET PROFESSIONAL PATIENTS
GET http://localhost:8080/cardiacrc/api/professionals/marcopolo/patients
Accept: application/json

### GET PROFESSIONAL PRESCTIPTIONS
GET http://localhost:8080/cardiacrc/api/professionals/marcopolo/prescriptions
Accept: application/json

### UPDATE PROFESSIONAL
PUT http://localhost:8080/cardiacrc/api/professionals/marcopolo
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYWNrc3BhcnJvdyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY0MDI5NjU2OH0.HIVqVe3er_EX4nUWAaHgP35G7XFFrxp4znxgj5c66CjPY9WlJ15aOvPBL63WKqrqHJDAR2eekI56OWoXOLTdZH_IzPXcopG81xjwBxeK0h0UoJc_9QMK9vlOjDZVG61frX1-60V7RtGsoudLbT7SaKJIDGa-NQlNz8zKCZJn29okkDy0vq6HY01iRXKME5pJCtlZFlEJhAHyoJCLULKp1OdnmrtHVCNpZmSZFGfylZtTYtI7T9mlafmdzchZXHLBwz6qhy3uROA6X5Y5ateTmyiOM88GHL3zBzkA8ROCh55ELadNrJHLW9H-c57NnXkd_uth7mDqpA5qaHj72-m8Og

{
  "passwordConfirmation": "123456",
  "licenseNumber": "12345679",
  "name": "Bryan",
  "password": "54321",
  "email": "bryan.sucks@no.com"
}

### DELETE PROFESSIONAL
DELETE http://localhost:8080/cardiacrc/api/professionals/ryanbaker
Accept: application/json



########## PATIENTS ##########

### CREATE PATIENT
POST http://localhost:8080/cardiacrc/api/patients
Content-Type: application/json

{ "username": "jackviole",
  "healthNumber": "498274982",
  "name": "Jack Viole",
  "password": "12345",
  "email": "jack.viole@mail.com",
  "professionalUsername": "ryanbaker"
}

### GET ALL PATIENTS
GET http://localhost:8080/cardiacrc/api/patients
Accept: application/json

### GET PATIENT DETAILS
GET http://localhost:8080/cardiacrc/api/patients/joaosalvador
Accept: application/json

### UPDATE PATIENT
PUT http://localhost:8080/cardiacrc/api/patients/jackviole
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYWNrc3BhcnJvdyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY0MDI5NjU2OH0.HIVqVe3er_EX4nUWAaHgP35G7XFFrxp4znxgj5c66CjPY9WlJ15aOvPBL63WKqrqHJDAR2eekI56OWoXOLTdZH_IzPXcopG81xjwBxeK0h0UoJc_9QMK9vlOjDZVG61frX1-60V7RtGsoudLbT7SaKJIDGa-NQlNz8zKCZJn29okkDy0vq6HY01iRXKME5pJCtlZFlEJhAHyoJCLULKp1OdnmrtHVCNpZmSZFGfylZtTYtI7T9mlafmdzchZXHLBwz6qhy3uROA6X5Y5ateTmyiOM88GHL3zBzkA8ROCh55ELadNrJHLW9H-c57NnXkd_uth7mDqpA5qaHj72-m8Og

{
  "passwordConfirmation": "123456",
  "healthNumber": "999999999",
  "name": "Jack Sparow",
  "password": "98765",
  "email": "cash@money.com",
  "professionalUsername": "tomasalves"
}

### DELETE PATIENT
DELETE http://localhost:8080/cardiacrc/api/patients/jackviole
Accept: application/json

### GET PATIENT PROGRAMS
GET http://localhost:8080/cardiacrc/api/patients/joaosalvador/programs
Accept: application/json

### ASSOCIATE PROFESSIONAL
PATCH http://localhost:8080/cardiacrc/api/patients/jackviole/addProfessional
Content-Type: application/json

{
  "username": "marcopolo"
}


########## ADMINISTRATORS ##########

### CREATE ADMINISTRATOR
POST http://localhost:8080/cardiacrc/api/administrators
Content-Type: application/json

{ "username": "admin1",
  "name": "ADMIN",
  "password": "000",
  "email": "admin@admin.un"
}

### GET ALL ADMINISTRATORS
GET http://localhost:8080/cardiacrc/api/administrators
Accept: application/json

### GET NUMBER OF ADMINISTRATORS
GET http://localhost:8080/cardiacrc/api/administrators/count
Accept: application/json


### GET ADMINISTRATOR DETAILS
GET http://localhost:8080/cardiacrc/api/administrators/admin1
Accept: application/json

### UPDATE ADMINISTRATOR
PUT http://localhost:8080/cardiacrc/api/administrators/admin1
Content-Type: application/json

{
  "name": "upADd ADMIN",
  "passwordConfirmation": "123456"
}

### DELETE ADMINISTRATOR
DELETE http://localhost:8080/cardiacrc/api/administrators/jacksparrow
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYWNrc3BhcnJvdyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY0MDI4OTk3N30.fVbEo5EkpLinvAeYIebh9B_4cSjF6WSjtkecvJlh6-adizs-3F4vY-DBP5tSO5vCjmIhtOmKWgsjYLbAwNteVu-Bf2pXCUI_z9KwDwC17aLsIqya5dprMx2JyLZ4iaqd8o-f-bDuv9qeOQDdPXeccvIMeOHNjo8sHvAxoDd2UZO1ouMhATyVsKoMmvDbhdmmW10AhXYOQGnx8qza3RY-3n-pc_J6ZLKAwJKbeQRIhkKR33ScJce4bS_Z9cqnpISg9wcp6hfG7HDvMeHm6GMf5F07Qal408dFhJs5Vtr1V60MQr5hW6bUS9zioqf2UW2Zne_UTs6hrpx9oU8465Rf0Q

### Get JWT token
POST http://localhost:8080/cardiacrc/api/auth/login
Content-Type: application/json

{
  "username": "jacksparrow",
  "password": "123456"
}

### Who am I?
GET http://localhost:8080/cardiacrc/api/auth/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYWNrc3BhcnJvdyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY0MDI4OTk3N30.fVbEo5EkpLinvAeYIebh9B_4cSjF6WSjtkecvJlh6-adizs-3F4vY-DBP5tSO5vCjmIhtOmKWgsjYLbAwNteVu-Bf2pXCUI_z9KwDwC17aLsIqya5dprMx2JyLZ4iaqd8o-f-bDuv9qeOQDdPXeccvIMeOHNjo8sHvAxoDd2UZO1ouMhATyVsKoMmvDbhdmmW10AhXYOQGnx8qza3RY-3n-pc_J6ZLKAwJKbeQRIhkKR33ScJce4bS_Z9cqnpISg9wcp6hfG7HDvMeHm6GMf5F07Qal408dFhJs5Vtr1V60MQr5hW6bUS9zioqf2UW2Zne_UTs6hrpx9oU8465Rf0Q

####
GET http://localhost:8080/cardiacrc/api/patients/joaosalvador/activePrescriptions
Accept: application/json


########## DATATYPES ##########

###GET ALL DATATYPES
GET http://localhost:8080/cardiacrc/api/dataTypes
Accept: application/json

###GET DATATYPE DETAILS
GET http://localhost:8080/cardiacrc/api/dataTypes/1
Accept: application/json

###CREATE DATATYPE
POST http://localhost:8080/cardiacrc/api/dataTypes
Content-Type: application/json

{
  "name": "nota",
  "unit": "%",
  "min": 0,
  "max": 20
}

###CREATE DATATYPE QUALITATIVE
POST http://localhost:8080/cardiacrc/api/dataTypes/2/qualitatives/
Content-Type: application/json

{
  "name": "FALHOU",
  "min": 0,
  "max": 10
}

###UPDATE DATATYPE
PUT http://localhost:8080/cardiacrc/api/dataTypes/2
Content-Type: application/json

{
  "name": "teste",
  "unit": "0 a 10",
  "min": 0,
  "max": 10
}

###UPDATE QUALITY DATATYPE
PUT http://localhost:8080/cardiacrc/api/dataTypes/2/qualitatives/4
Content-Type: application/json

{
  "name": "ACERTOU",
  "min": 5,
  "max": 8
}

###DELETE DATATYPE
DELETE http://localhost:8080/cardiacrc/api/dataTypes/2
Accept: application/json

###DELETE QUANTITATY DATATYPE
DELETE http://localhost:8080/cardiacrc/api/dataTypes/1/qualitatives/3
Accept: application/json