########## ADMINISTRATORS ##########
### CREATE ADMINISTRATOR
POST http://localhost:8080/cardiacrc/api/administrators
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTI4NTV9.DFX_ZYLn73h77ehHM_f-AwnSLtPkHUKbeGvV65VCVa1nO2J2m-P-YM1bx43zGbUxSopg2t3V2FUex4ASyeRp08wGvVFmwGq56PBcmLQ-QKbUSr4qC2s0_-5OcqEE8dqVZyfr32MK1COtcVJxaiMLTNjNNNmELSdUTdZOERVYlv0rJTOpesXNYIgDnqRXO0oFHgnsjQjJDDIKoxVsCqjfII4msroWvLYk7dACpUu3fVdqKr-LXvW-nvxOYcA_kynCjWw1BST_-iXvaVeM_MGePw0h2JGtSDczN6hL92wqCk9uKjP7T1EL419o_ZeQ2JBYYLLuRseK4SV6jNcx2dNiuA

{ "username": "admin20",
  "name": "ADMIN",
  "password": "000",
  "email": "admin@admin.un"
}

### GET ALL ADMINISTRATORS
GET http://localhost:8080/cardiacrc/api/administrators
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTI4NTV9.DFX_ZYLn73h77ehHM_f-AwnSLtPkHUKbeGvV65VCVa1nO2J2m-P-YM1bx43zGbUxSopg2t3V2FUex4ASyeRp08wGvVFmwGq56PBcmLQ-QKbUSr4qC2s0_-5OcqEE8dqVZyfr32MK1COtcVJxaiMLTNjNNNmELSdUTdZOERVYlv0rJTOpesXNYIgDnqRXO0oFHgnsjQjJDDIKoxVsCqjfII4msroWvLYk7dACpUu3fVdqKr-LXvW-nvxOYcA_kynCjWw1BST_-iXvaVeM_MGePw0h2JGtSDczN6hL92wqCk9uKjP7T1EL419o_ZeQ2JBYYLLuRseK4SV6jNcx2dNiuA

### GET COUNTS
GET http://localhost:8080/cardiacrc/api/administrators/count
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTI4NTV9.DFX_ZYLn73h77ehHM_f-AwnSLtPkHUKbeGvV65VCVa1nO2J2m-P-YM1bx43zGbUxSopg2t3V2FUex4ASyeRp08wGvVFmwGq56PBcmLQ-QKbUSr4qC2s0_-5OcqEE8dqVZyfr32MK1COtcVJxaiMLTNjNNNmELSdUTdZOERVYlv0rJTOpesXNYIgDnqRXO0oFHgnsjQjJDDIKoxVsCqjfII4msroWvLYk7dACpUu3fVdqKr-LXvW-nvxOYcA_kynCjWw1BST_-iXvaVeM_MGePw0h2JGtSDczN6hL92wqCk9uKjP7T1EL419o_ZeQ2JBYYLLuRseK4SV6jNcx2dNiuA

### GET ADMINISTRATOR DETAILS
GET http://localhost:8080/cardiacrc/api/administrators/admin1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTI4NTV9.DFX_ZYLn73h77ehHM_f-AwnSLtPkHUKbeGvV65VCVa1nO2J2m-P-YM1bx43zGbUxSopg2t3V2FUex4ASyeRp08wGvVFmwGq56PBcmLQ-QKbUSr4qC2s0_-5OcqEE8dqVZyfr32MK1COtcVJxaiMLTNjNNNmELSdUTdZOERVYlv0rJTOpesXNYIgDnqRXO0oFHgnsjQjJDDIKoxVsCqjfII4msroWvLYk7dACpUu3fVdqKr-LXvW-nvxOYcA_kynCjWw1BST_-iXvaVeM_MGePw0h2JGtSDczN6hL92wqCk9uKjP7T1EL419o_ZeQ2JBYYLLuRseK4SV6jNcx2dNiuA

### UPDATE ADMINISTRATOR
PUT http://localhost:8080/cardiacrc/api/administrators/admin1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTI4NTV9.DFX_ZYLn73h77ehHM_f-AwnSLtPkHUKbeGvV65VCVa1nO2J2m-P-YM1bx43zGbUxSopg2t3V2FUex4ASyeRp08wGvVFmwGq56PBcmLQ-QKbUSr4qC2s0_-5OcqEE8dqVZyfr32MK1COtcVJxaiMLTNjNNNmELSdUTdZOERVYlv0rJTOpesXNYIgDnqRXO0oFHgnsjQjJDDIKoxVsCqjfII4msroWvLYk7dACpUu3fVdqKr-LXvW-nvxOYcA_kynCjWw1BST_-iXvaVeM_MGePw0h2JGtSDczN6hL92wqCk9uKjP7T1EL419o_ZeQ2JBYYLLuRseK4SV6jNcx2dNiuA

{
  "name": "upADd ADMIN",
  "passwordConfirmation": "123456"
}

### DELETE ADMINISTRATOR
DELETE http://localhost:8080/cardiacrc/api/administrators/admin20
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTI4NTV9.DFX_ZYLn73h77ehHM_f-AwnSLtPkHUKbeGvV65VCVa1nO2J2m-P-YM1bx43zGbUxSopg2t3V2FUex4ASyeRp08wGvVFmwGq56PBcmLQ-QKbUSr4qC2s0_-5OcqEE8dqVZyfr32MK1COtcVJxaiMLTNjNNNmELSdUTdZOERVYlv0rJTOpesXNYIgDnqRXO0oFHgnsjQjJDDIKoxVsCqjfII4msroWvLYk7dACpUu3fVdqKr-LXvW-nvxOYcA_kynCjWw1BST_-iXvaVeM_MGePw0h2JGtSDczN6hL92wqCk9uKjP7T1EL419o_ZeQ2JBYYLLuRseK4SV6jNcx2dNiuA