########## DATATYPES ##########

###GET ALL DATATYPES
GET http://localhost:8080/cardiacrc/api/dataTypes
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

###GET DATATYPE DETAILS
GET http://localhost:8080/cardiacrc/api/dataTypes/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

###CREATE DATATYPE
POST http://localhost:8080/cardiacrc/api/dataTypes
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

{
  "name": "nota",
  "unit": "%",
  "min": 0,
  "max": 20
}

###CREATE DATATYPE QUALITATIVE
POST http://localhost:8080/cardiacrc/api/dataTypes/2/qualitatives/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

{
  "name": "Reprovou",
  "min": 0,
  "max": 10
}

###UPDATE DATATYPE
PUT http://localhost:8080/cardiacrc/api/dataTypes/2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

{
  "name": "teste",
  "unit": "0 a 10",
  "min": 0,
  "max": 10
}

###UPDATE QUALITY DATATYPE
PUT http://localhost:8080/cardiacrc/api/dataTypes/2/qualitatives/4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

{
  "name": "Aprovado",
  "min": 5,
  "max": 8
}

###DELETE DATATYPE
DELETE http://localhost:8080/cardiacrc/api/dataTypes/2
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

###DELETE QUANTITATY DATATYPE
DELETE http://localhost:8080/cardiacrc/api/dataTypes/1/qualitatives/3
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MTM0MTR9.JXu52BWPzSZaOrn9dF00iW1ZJoT7AS5ZycNMnBf-rwaTF7A2HPxsTm17bym_Rr6gCUmRkHktzSF_-q-K1yIu6AP26ar9QMfTqdd-4mHl8I_ILf4s1BVHecXaj4cgOQmA_C3FzClTUXg1h8N3Wk0s2kzQrSqhr9HXlSYgPxa1QMs6wDYH5fM4GrFXBKCxD-VMTK4LQcmYLuAxCVCe9W5pzupW8N32k6TZJkyQQvPu4tsxqy1IuolhVnd68wdas2TBjwarPCrQcktrSrmg9-q6iYHRb77ATiJUSTYOhFxA2NgAphVUvryZY2L4ISPWTORdBehbKDjQEx0hitQtDvV7Dg

### EXPORT DATATYPES
GET http://localhost:8080/cardiacrc/api/dataTypes/export HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEzMjAzMDd9.ZYdPJntoWaoyW4s1ytglKFEMF7--WcfkcaywVdOEjGS0zTZaCv0RSw3AcNCY85SIvHY7dqAXcG_IsHhcjEAc3-6pTQeZAY_TE70IzYsyfj_bcflr3zUbFiablJEvLTyZeTldNlJ2pxb0PqLUBLZUwaxJKkMrdaA09fTm6ZdyCa_hw7PvgLAxYyUoIKxiudExuxnTjcu6F0Otj4RebBS79DdvPMBlZm5uP0RLGKXq_XEMCKbz1kd8MD_h9Kam_jTYplq8AdtaY0qUP5laLjAjayOngyMDxwlWF2c7ntTiHXr_lQyad_th1jvmgNPaQ02V6KsM8mWWW1USk7sf4axlJQ
