########## OBSERVATIONS ##########

###CREATE OBSERVATION
POST http://localhost:8080/cardiacrc/api/observations
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2Fvc2FsdmFkb3IiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiUGF0aWVudCJdLCJleHAiOjE2NDA4MzA0NjJ9.Kj7HoZfv_Ymnc63_Oye6f_NeYzPPUXrQAdW3YHdUIqFR75e5HJk_t6dxAzWhiurDn6ZMsEbIUiOvETXiP2VMVsRPnd_RDpLMuu3Cw7AxEr1KjcpxNxgWlMeURnRXD8jtfFD_ABb3vOKovvLHqgkvrxUh6JX2oLkYp0ZEF2fdKh2UTORFYfTkIX-RPIq43xwZLEq-NtHf27_7MrquV7NG5qWwV6ejUDkzI7OTp0R2WVOE2C9M1ZLIpTD5mNedfXr9tWRpgkUnz-l334zG-RK1W8my0GRgh7_UUdaAs_rVA7yOmPB75hS43SskE9k1UwS8X91l4AR08oXhilIaqJydhw

{
  "patientUsername": "joaosalvador",
  "value":0.5,
  "dataTypeId": 1
}

###GET ALL OBSERVATION
GET http://localhost:8080/cardiacrc/api/observations
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2Fvc2FsdmFkb3IiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiUGF0aWVudCJdLCJleHAiOjE2NDA4MzA0NjJ9.Kj7HoZfv_Ymnc63_Oye6f_NeYzPPUXrQAdW3YHdUIqFR75e5HJk_t6dxAzWhiurDn6ZMsEbIUiOvETXiP2VMVsRPnd_RDpLMuu3Cw7AxEr1KjcpxNxgWlMeURnRXD8jtfFD_ABb3vOKovvLHqgkvrxUh6JX2oLkYp0ZEF2fdKh2UTORFYfTkIX-RPIq43xwZLEq-NtHf27_7MrquV7NG5qWwV6ejUDkzI7OTp0R2WVOE2C9M1ZLIpTD5mNedfXr9tWRpgkUnz-l334zG-RK1W8my0GRgh7_UUdaAs_rVA7yOmPB75hS43SskE9k1UwS8X91l4AR08oXhilIaqJydhw

###GET OBSERVATION
GET http://localhost:8080/cardiacrc/api/observations/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2Fvc2FsdmFkb3IiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiUGF0aWVudCJdLCJleHAiOjE2NDA4MzA0NjJ9.Kj7HoZfv_Ymnc63_Oye6f_NeYzPPUXrQAdW3YHdUIqFR75e5HJk_t6dxAzWhiurDn6ZMsEbIUiOvETXiP2VMVsRPnd_RDpLMuu3Cw7AxEr1KjcpxNxgWlMeURnRXD8jtfFD_ABb3vOKovvLHqgkvrxUh6JX2oLkYp0ZEF2fdKh2UTORFYfTkIX-RPIq43xwZLEq-NtHf27_7MrquV7NG5qWwV6ejUDkzI7OTp0R2WVOE2C9M1ZLIpTD5mNedfXr9tWRpgkUnz-l334zG-RK1W8my0GRgh7_UUdaAs_rVA7yOmPB75hS43SskE9k1UwS8X91l4AR08oXhilIaqJydhw

###DELETE OBSERVATION
DELETE http://localhost:8080/cardiacrc/api/observations/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2Fvc2FsdmFkb3IiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiUGF0aWVudCJdLCJleHAiOjE2NDA4MTM1Njh9.Hi1Rt4htieLRPt77lrAtfr5IZ5jtlC2d402uR7PhbJr1WG2SAOYjDyayE325FPi2b8Fo9AFjT4W22jQmBCFniQA4dQxvw0jr7xMfOrnhT0v35i6y83mN0036y7zUmazYL2eZwoCYszZnQjvT0Yjqdp0YUMjcG1wB6Te7UrP2i0e3BFu5ree_QG_8FyId6Mej-UX-BVKpSSJjf9KYM1mF0HRx4-0AlSbtEGu9_4YROPyYBHd3lKGKpl-dKpLQGicz2oa-EgnATyJ4eQvRGesh3MX4KP4Am9-UVff9Z6LK2n7MWGwTWfQFE47Hl_rN6leMtbXZUXYcn-KILh89_BJUfA

