########## PATIENTS ##########

### CREATE PATIENT
POST http://localhost:8080/cardiacrc/api/patients
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqb2Fvc2FsdmFkb3IiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiUGF0aWVudCJdLCJleHAiOjE2NDA4MTM1Njh9.Hi1Rt4htieLRPt77lrAtfr5IZ5jtlC2d402uR7PhbJr1WG2SAOYjDyayE325FPi2b8Fo9AFjT4W22jQmBCFniQA4dQxvw0jr7xMfOrnhT0v35i6y83mN0036y7zUmazYL2eZwoCYszZnQjvT0Yjqdp0YUMjcG1wB6Te7UrP2i0e3BFu5ree_QG_8FyId6Mej-UX-BVKpSSJjf9KYM1mF0HRx4-0AlSbtEGu9_4YROPyYBHd3lKGKpl-dKpLQGicz2oa-EgnATyJ4eQvRGesh3MX4KP4Am9-UVff9Z6LK2n7MWGwTWfQFE47Hl_rN6leMtbXZUXYcn-KILh89_BJUfA

{ "username": "jackviole",
  "healthNumber": "498274982",
  "name": "Jack Viole",
  "password": "12345",
  "email": "jack.viole@mail.com",
  "professionalUsername": "ryanbaker"
}

### GET ALL PATIENTS
GET http://localhost:8080/cardiacrc/api/patients
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEwODkyODZ9.cqNWh3Oekfv4KMcqBECDDk6ozQwe1vguQ1NEjv0Uv6D8V5KCLbi1PEjh2-niDgTCcJIrmg8MyzJ7W9B5JE2o8TCRwCeHuOEsiYudoTUAD0_5xU3bhpFm00Ghg9W-D6DU8-7Jz-HIViDOAjCCUVPmQ4HSJ9bqEnE2r7FJt_H4dOkUbzzAgfLvAYbZ04IIJeltciC_-hok7XsLUYo9I6jofmr4TwK2hF1uzVo8T_FpNBcpx3IWL41mZpcOF3q-uZlCzHXwA8WjjEf5HiBQWkCMc7rBHUSkA-lEeamGvK09kspA3Zn7S8sSBM36YyuUvVccVqPE1Wfi3U9oUDNEQo0l_g

### GET PATIENT DETAILS
GET http://localhost:8080/cardiacrc/api/patients/joaosalvador
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEwODkyODZ9.cqNWh3Oekfv4KMcqBECDDk6ozQwe1vguQ1NEjv0Uv6D8V5KCLbi1PEjh2-niDgTCcJIrmg8MyzJ7W9B5JE2o8TCRwCeHuOEsiYudoTUAD0_5xU3bhpFm00Ghg9W-D6DU8-7Jz-HIViDOAjCCUVPmQ4HSJ9bqEnE2r7FJt_H4dOkUbzzAgfLvAYbZ04IIJeltciC_-hok7XsLUYo9I6jofmr4TwK2hF1uzVo8T_FpNBcpx3IWL41mZpcOF3q-uZlCzHXwA8WjjEf5HiBQWkCMc7rBHUSkA-lEeamGvK09kspA3Zn7S8sSBM36YyuUvVccVqPE1Wfi3U9oUDNEQo0l_g

### UPDATE PATIENT
PUT http://localhost:8080/cardiacrc/api/patients/jackviole
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJqYWNrc3BhcnJvdyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTY0MDI5NjU2OH0.HIVqVe3er_EX4nUWAaHgP35G7XFFrxp4znxgj5c66CjPY9WlJ15aOvPBL63WKqrqHJDAR2eekI56OWoXOLTdZH_IzPXcopG81xjwBxeK0h0UoJc_9QMK9vlOjDZVG61frX1-60V7RtGsoudLbT7SaKJIDGa-NQlNz8zKCZJn29okkDy0vq6HY01iRXKME5pJCtlZFlEJhAHyoJCLULKp1OdnmrtHVCNpZmSZFGfylZtTYtI7T9mlafmdzchZXHLBwz6qhy3uROA6X5Y5ateTmyiOM88GHL3zBzkA8ROCh55ELadNrJHLW9H-c57NnXkd_uth7mDqpA5qaHj72-m8Og

{
  "passwordConfirmation": "123456",
  "healthNumber": "999999999",
  "name": "Jack Sparow",
  "password": "98765",
  "email": "cash@money.com",
  "professionalUsername": "tomasalves"
}

### DELETE PATIENT
DELETE http://localhost:8080/cardiacrc/api/patients/jackviole
Accept: application/json

### GET PATIENT PROGRAMS
GET http://localhost:8080/cardiacrc/api/patients/joaosalvador/programs
Accept: application/json

### ASSOCIATE PROFESSIONAL
PATCH http://localhost:8080/cardiacrc/api/patients/jackviole/addProfessional
Content-Type: application/json

{
  "username": "marcopolo"
}