########## PRESCRIPTIONS ##########

### CREATE PRESCRIPTION
POST http://localhost:8080/cardiacrc/api/prescriptions
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

{
  "description": "Drink Water",
  "name": "Drink",
  "frequency": "7 times per day",
  "programId": 1
}

### GET ALL PRESCRIPTIONS
GET http://localhost:8080/cardiacrc/api/prescriptions
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MjY1MzZ9.S2vHfN2QLsZCqeW_HobmaYUZaDgA6SeZrz2y9uqLpW5613rQmEexjmO_Gz0yAQVoXmcLb0ncrhv9Q-eh2D0xhcVKb0KTwCfg1qI2yVRK80Ih_y5Yfcpo4OKBleKf_donKxthC6tz1nUUpKMxnKGK8MIuiiQeQyzw6dDUKlBCQtAM819CfPfT2H85zGxa4rZZy1U3_2pBxouaRWYRqSkvbJP4F4jcbAjhOIlgFEZ75EEVQ_cDovepPTy76nhW8LzrYOiUZrErCrIVO6yPhYfAmjn-dEw9KgODBrD-8XMh3zDTkb_OHQ8Gc0uILyMbRHvwRjmqWD9OSu1iA2JW1TpWhA

### GET PRESCRIPTION DETAILS
GET http://localhost:8080/cardiacrc/api/prescriptions/4
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

### UPDATE PRESCRIPTION
PUT http://localhost:8080/cardiacrc/api/prescriptions/4
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

{
  "name": "Eat",
  "description": "Eat healthy"
}

### DELETE PRESCRIPTION
DELETE http://localhost:8080/cardiacrc/api/prescriptions/4
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ