########## PROFESSIONALS ##########

### CREATE PROFESSIONAL
POST http://localhost:8080/cardiacrc/api/professionals
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA5ODI3ODl9.N8uC7z6YBIzSsygKnN1GpPe1M_4_RtBNW2JZKBEYRpOssU8BNEKVuV151ruSvAwN12IpvPAKOjNSBypBimSRO4XF2sJ2pY06vS5KZQjtB2-tm5cwXwOrZXhhCo9IF5rUrvGn5UT-jw0tXMIzBvh-osz6yXMfELkS1R1tGebDLFE_f6HA3uHNatW8vQ5pnMQuZ9Ff513MKx7noSQSgFckqqgZwhUqcmqfAcnU9-k3oS895Zl174Yx1N_yNz4Fhdj_lITeXPv6FdizFcABA14Hr7PedDaBdJpiUsUubcBgkJT4CNxazBx9VjjpGw1BSGzKfxYXQMpGj69bAuXiRPYT_g

{ "username": "ryanbaker",
  "licenseNumber": "438942035",
  "name": "Ryan Baker",
  "password": "12345",
  "email": "ryan.baker@mail.com",
  "type": 1
}

### GET ALL PROFESSIONALS
GET http://localhost:8080/cardiacrc/api/professionals
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDEwNjczOTh9.XYSdVfwhpc0icQyBrjuTqBkFDkXK4Ht9u2A69vHt4-pvEmhMiAqk8QKJ2qfY2boXsDHf7P7Dnz-fN6UDMcsDgKdankJFXSOWHu_2OjnQygUJFrSnKUQ9OI-xCFaL5X7zJDxlV54blu8XjDeKbbEpH_rViIfWUbR0HRbsBqgpIC1t36yIT0rehbqMhwmN8tLfaZPyxUsy6l1mqSAOuq2XIOiQjaFchbeAn_uYeXCFkzr-r-xPMXiDC7TkhVWmtXPngFHj43xl50JyWRf4DR-NUcTXo28gEfXtYnXsvdBLnB5kWN-8Bnyc9GikyQKKyD53fIx6a6HkrADFXHEhL6GkYQ

### GET PROFESSIONAL DETAILS
GET http://localhost:8080/cardiacrc/api/professionals/marcopolo
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA5ODI3ODl9.N8uC7z6YBIzSsygKnN1GpPe1M_4_RtBNW2JZKBEYRpOssU8BNEKVuV151ruSvAwN12IpvPAKOjNSBypBimSRO4XF2sJ2pY06vS5KZQjtB2-tm5cwXwOrZXhhCo9IF5rUrvGn5UT-jw0tXMIzBvh-osz6yXMfELkS1R1tGebDLFE_f6HA3uHNatW8vQ5pnMQuZ9Ff513MKx7noSQSgFckqqgZwhUqcmqfAcnU9-k3oS895Zl174Yx1N_yNz4Fhdj_lITeXPv6FdizFcABA14Hr7PedDaBdJpiUsUubcBgkJT4CNxazBx9VjjpGw1BSGzKfxYXQMpGj69bAuXiRPYT_g

### GET PROFESSIONAL PATIENTS
GET http://localhost:8080/cardiacrc/api/professionals/tomasalves/patients
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA5ODMwMjF9.DPTBUb4x-Eemb-2s0T-UgjmCVRnB9neZfrwsr7A1MT8ccwK4wczCwl2rtfuJAagykA50GKiFRHn81kYv7XXdyCmxQWgwknQvYqn3WRtID_70rZH5whEfTiUR56wpOcL1Q7umQdxVeZwCCpfpceaoj_EqqQTcnREGQTkP9Uz67Ty-aaCyY_DN4iJUr1RYevYxDxQ2Q-XC2DvMbXN3WYHx5rSTr423RqRoOteO8RooBq2m6R72rXfpJNm6EJKc8XgaUNsrazfytIKe_P4oM9z4xbBuLDiNWJ-pZ9vj0RJUtlzKBur8fm-TOxgvmli6Ea2tFN2YFyrRJriIxT8VUiscQg

### GET PROFESSIONAL PRESCTIPTIONS
GET http://localhost:8080/cardiacrc/api/professionals/tomasalves/prescriptions
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA5ODMwMjF9.DPTBUb4x-Eemb-2s0T-UgjmCVRnB9neZfrwsr7A1MT8ccwK4wczCwl2rtfuJAagykA50GKiFRHn81kYv7XXdyCmxQWgwknQvYqn3WRtID_70rZH5whEfTiUR56wpOcL1Q7umQdxVeZwCCpfpceaoj_EqqQTcnREGQTkP9Uz67Ty-aaCyY_DN4iJUr1RYevYxDxQ2Q-XC2DvMbXN3WYHx5rSTr423RqRoOteO8RooBq2m6R72rXfpJNm6EJKc8XgaUNsrazfytIKe_P4oM9z4xbBuLDiNWJ-pZ9vj0RJUtlzKBur8fm-TOxgvmli6Ea2tFN2YFyrRJriIxT8VUiscQg

### UPDATE PROFESSIONAL
PUT http://localhost:8080/cardiacrc/api/professionals/marcopolo
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MjY1MzZ9.S2vHfN2QLsZCqeW_HobmaYUZaDgA6SeZrz2y9uqLpW5613rQmEexjmO_Gz0yAQVoXmcLb0ncrhv9Q-eh2D0xhcVKb0KTwCfg1qI2yVRK80Ih_y5Yfcpo4OKBleKf_donKxthC6tz1nUUpKMxnKGK8MIuiiQeQyzw6dDUKlBCQtAM819CfPfT2H85zGxa4rZZy1U3_2pBxouaRWYRqSkvbJP4F4jcbAjhOIlgFEZ75EEVQ_cDovepPTy76nhW8LzrYOiUZrErCrIVO6yPhYfAmjn-dEw9KgODBrD-8XMh3zDTkb_OHQ8Gc0uILyMbRHvwRjmqWD9OSu1iA2JW1TpWhA

{
  "passwordConfirmation": "123456",
  "licenseNumber": "12345679",
  "name": "Bryan",
  "password": "54321",
  "email": "bryan.sucks@no.com"
}

### DELETE PROFESSIONAL
DELETE http://localhost:8080/cardiacrc/api/professionals/ryanbaker
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbjEiLCJpc3MiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJhdWQiOiJqd3QtYXVkaWVuY2UiLCJncm91cHMiOlsiQWRtaW5pc3RyYXRvciJdLCJleHAiOjE2NDA4MjY1MzZ9.S2vHfN2QLsZCqeW_HobmaYUZaDgA6SeZrz2y9uqLpW5613rQmEexjmO_Gz0yAQVoXmcLb0ncrhv9Q-eh2D0xhcVKb0KTwCfg1qI2yVRK80Ih_y5Yfcpo4OKBleKf_donKxthC6tz1nUUpKMxnKGK8MIuiiQeQyzw6dDUKlBCQtAM819CfPfT2H85zGxa4rZZy1U3_2pBxouaRWYRqSkvbJP4F4jcbAjhOIlgFEZ75EEVQ_cDovepPTy76nhW8LzrYOiUZrErCrIVO6yPhYfAmjn-dEw9KgODBrD-8XMh3zDTkb_OHQ8Gc0uILyMbRHvwRjmqWD9OSu1iA2JW1TpWhA