########## PROGRAMS ##########

###CREATE PROGRAM
POST http://localhost:8080/cardiacrc/api/programs
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

{
  "name": "My firstProgram",
  "duration": 2,
  "professionalUsername": "marcopolo",
  "patientUsername": "joaosalvador",
  "prescriptionIds": [1,2,3]
}

###GET ALL PROGRAMS
POST http://localhost:8080/cardiacrc/api/programs
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

###GET PROGRAM DETAILS
GET http://localhost:8080/cardiacrc/api/programs/2
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

###UPDATE PROGRAM
PATCH http://localhost:8080/cardiacrc/api/programs/2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

{
  "duration": 6
}

###DELETE PROGRAM
DELETE http://localhost:8080/cardiacrc/api/programs/2
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

###ADD PRESCRIPTION
PATCH http://localhost:8080/cardiacrc/api/programs/2/addPrescription
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

{
  "id": 1
}

###REMOVE PRESCRIPTION
PATCH http://localhost:8080/cardiacrc/api/programs/2/removePrescription
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0b21hc2FsdmVzIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIlByb2Zlc3Npb25hbCJdLCJleHAiOjE2NDA4MjY0ODN9.WDKtj7I05lKh21dkG_HV5iKZKZZohsl2byTj8xEZivPfFAKopbjYtP1qp_MlyV2w6-jGDcFOpGg_hxWGUzu52I8TKDMqSUYi1LVR3YZG8ybg9pY1ahhNrQxgjThgiD1uuhS-XRVcu0i7QW9-zATyV5D4sjdoZezfSTR9zPCNmsGbX05LRDuzvksVpkSFk_hiCnSJzyIz-ulb-yXrIN46jDhf1dO8Z745toH0IlNQd_JhCY7MRevDyz4Xl5TB4JiDAm4KunRP8Yfa-9rVFTzUZ_za_ae2XTpKRlv0jFIjR7jGs6n-u9XOgxOJzDIwWZIeD37gvcQjpVq_iJXzDT8kJQ

{
  "id": 1
}




